// frontend/client-vue/src/components/LiquidBackground.vue
<template>
  <div class="fixed inset-0 overflow-hidden pointer-events-none z-0">
    <div class="absolute inset-0 bg-gradient-to-br from-blue-950/20 via-background to-indigo-950/20"></div>
    
    <!-- Liquid Orbs -->
    <div class="absolute top-10 left-10 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl animate-liquid-flow"></div>
    <div class="absolute top-1/2 right-20 w-64 h-64 bg-indigo-500/15 rounded-full blur-2xl animate-liquid-flow" style="animation-delay: -5s;"></div>
    <div class="absolute bottom-20 left-1/3 w-80 h-80 bg-emerald-500/10 rounded-full blur-3xl animate-liquid-flow" style="animation-delay: -10s;"></div>
    <div class="absolute top-1/4 right-1/3 w-48 h-48 bg-purple-500/12 rounded-full blur-2xl animate-liquid-flow" style="animation-delay: -15s;"></div>
    
    <!-- Subtle Grid Pattern -->
    <div class="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:4rem_4rem] opacity-30"></div>
  </div>
</template>

<script setup lang="ts">
// No script needed for this purely visual component
</script>

<style scoped>
/* Component-specific styles if needed */
</style>

// frontend/client/src/components/LiquidBackground.tsx
export function LiquidBackground() {
  return (
    <div 
      className="fixed inset-0 -z-10 pointer-events-none overflow-hidden"
      aria-hidden="true"
    >
      {/* Animated liquid background */}
      <div className="absolute inset-0 bg-gradient-to-br from-background via-background to-card">
        {/* Floating orbs */}
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/5 rounded-full blur-3xl animate-liquid-flow" />
        <div className="absolute top-3/4 right-1/4 w-80 h-80 bg-chart-2/10 rounded-full blur-3xl animate-liquid-flow" style={{ animationDelay: '5s' }} />
        <div className="absolute bottom-1/4 left-1/3 w-72 h-72 bg-chart-3/8 rounded-full blur-3xl animate-liquid-flow" style={{ animationDelay: '10s' }} />
        
        {/* Subtle grid overlay */}
        <div className="absolute inset-0 opacity-[0.02]">
          <div className="h-full w-full" style={{ 
            backgroundImage: `linear-gradient(rgba(255,255,255,0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.1) 1px, transparent 1px)`,
            backgroundSize: '50px 50px'
          }} />
        </div>
      </div>
    </div>
  );
}
